name: Continous Integration

on:
  pull_request:
    branches: [ main ]
  
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: pip uninstall pylint
      - run: pip install -r test.requirements.txt
      - run: pytest /tests/test.py
